---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    attributes:
      ruby:
        version: '2.3'
    run_list:
      - recipe[apt::default]
      - recipe[bcs_ruby::default]
