---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: latest
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
    attributes:
      bcs_ruby:
        version: '2.3'
  - name: ubuntu-16.04
    attributes:
      bcs_ruby:
        version: '2.3'
  - name: ubuntu-18.04
    attributes:
      bcs_ruby:
        version: '2.5'
suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[bcs_ruby::default]
